_target_: src.scenario.gz_exp_ppo.PPOScenarioWrapper

simulator: ~ simulator
running_objective: ~ running_objective
device: "cuda:0"
total_timesteps: 1000000
gamma: 0.99
policy_lr: 3.0e-4
anneal_lr: True
num_steps: 2048
gae_lambda: 0.95
update_epoch: 10
num_minibatches: 32
clip_coef: 0.2
norm_adv: True
clip_vloss: True
vf_coef: 0.5
ent_coef: 0.0
max_grad_norm: 0.5
target_kl: null
reset_rb_each_task: False
checkpoint_dirpath: null
seed: 42
env: ""