_target_: src.stanley_policy.StanleyController

control_gain: 2.5
softening_gain: 0.7
yaw_rate_gain: 0.5
steering_damp_gain: 0.0
system: ~ system
max_abs_linear_vel: 1.0

action_bounds: = np.array([[-1.2, 1.2], [-1.7, 1.7]])
trajectory_gen:
  _target_: src.trajectory.TrajectoryGenerator
  init_state: $ initial_conditions.state_init
  trajectory_type: Linear
