_target_: src.policy.ThreeWheeledRobotCALFQ

# action_bounds: = np.array([[-0.22, 0.22], [-2.84, 2.84]])
system: ~ system
# R1_diag: = [1, 10, 1, 0, 0]
weight_path: = None
critic_desired_decay: = 1e-5
critic_low_kappa_coeff: = 1e-1
critic_up_kappa_coeff: = 1e3
