_target_: src.scenario.calf_agent.calfv.AgentCALFV

env:
  _target_: src.rgenv.RgEnv
  simulator: ~ simulator
  running_objective: ~ running_objective
safe_policy:
  _target_: src.policy.LunarLanderStabilizingPolicy
  angle_pd_coefs: = [80, 20]
  x_pd_coefs: = [10, 40]
sampling_time: $ common.sampling_time
critic_safe_decay_param: 0.01
critic_regularization_param: 10000
critic_lb_parameter: 1.0E-2
critic_td_n: 1
critic_batch_size: 3
relax_probability_min: 0.0000
relax_probability_max: 0.46222
relax_probability_stabilize_global_step: 9000
is_propagate_safe_weights: True
critic_model:
  _target_: regelum.model.ModelQuadLin
  quad_matrix_type: symmetric
  is_with_linear_terms: False
  dim_inputs: 6
  add_random_init_noise: True
running_objective: ~ running_objective
observer:
  _target_: regelum.observer.ObserverReference
  reference: = numpy.array([0., 1.0, 0.0, 0.0, 0.0, 0.0])