_target_: regelum.objective.RunningObjective
model:
  _target_: regelum.model.ModelQuadLin
  quad_matrix_type: diagonal
  is_with_linear_terms: false
  weights: = numpy.array([10.0, 10.0, 2., 0., 0.])